-- public.customers definition

-- Drop table

-- DROP TABLE public.customers;

CREATE TABLE public.customers (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	delivery_address varchar(255) NULL,
	join_date timestamp(6) NULL,
	phone_number varchar(30) NULL,
	CONSTRAINT customers_pkey PRIMARY KEY (id)
);


-- public.dishes definition

-- Drop table

-- DROP TABLE public.dishes;

CREATE TABLE public.dishes (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	description text NULL,
	"name" varchar(255) NOT NULL,
	price float8 NOT NULL,
	CONSTRAINT dishes_pkey PRIMARY KEY (id)
);


-- public.ingredients definition

-- Drop table

-- DROP TABLE public.ingredients;

CREATE TABLE public.ingredients (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	allergen text NULL,
	"name" varchar(255) NOT NULL,
	price float8 NOT NULL,
	unit varchar(7) NOT NULL,
	CONSTRAINT ingredients_pkey PRIMARY KEY (id)
);


-- public.amount_of_ingredients definition

-- Drop table

-- DROP TABLE public.amount_of_ingredients;

CREATE TABLE public.amount_of_ingredients (
	amount float8 NOT NULL,
	dish_id int8 NOT NULL,
	ingredient_id int8 NOT NULL,
	CONSTRAINT amount_of_ingredients_pkey PRIMARY KEY (dish_id, ingredient_id),
	CONSTRAINT fk57gksvlw9care7g5hka3g4phk FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id),
	CONSTRAINT fklki3dijf2tihb0a5va0mej5h FOREIGN KEY (dish_id) REFERENCES public.dishes(id)
);


-- public.orders definition

-- Drop table

-- DROP TABLE public.orders;

CREATE TABLE public.orders (
	id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
	deliver_date timestamp(6) NULL,
	delivery bool NOT NULL,
	order_date timestamp(6) NULL,
	self_takeout bool NOT NULL,
	takeout bool NOT NULL,
	total_price float8 NOT NULL,
	customer_id int8 NULL,
	CONSTRAINT orders_pkey PRIMARY KEY (id),
	CONSTRAINT fkpxtb8awmi0dk6smoh2vp1litg FOREIGN KEY (customer_id) REFERENCES public.customers(id)
);


-- public.order_items definition

-- Drop table

-- DROP TABLE public.order_items;

CREATE TABLE public.order_items (
	price float8 NOT NULL,
	quantity int4 NOT NULL,
	dish_id int8 NOT NULL,
	order_id int8 NOT NULL,
	CONSTRAINT order_items_pkey PRIMARY KEY (dish_id, order_id),
	CONSTRAINT fkbioxgbv59vetrxe0ejfubep1w FOREIGN KEY (order_id) REFERENCES public.orders(id),
	CONSTRAINT fkn06bdypik73hotpxvefsrtn77 FOREIGN KEY (dish_id) REFERENCES public.dishes(id)
);


-- public.additional_ingredients definition

-- Drop table

-- DROP TABLE public.additional_ingredients;

CREATE TABLE public.additional_ingredients (
	amount_additional int4 NOT NULL,
	dish_id int8 NOT NULL,
	ingredient_id int8 NOT NULL,
	order_id int8 NOT NULL,
	CONSTRAINT additional_ingredients_pkey PRIMARY KEY (dish_id, ingredient_id, order_id),
	CONSTRAINT fkebptyxvas1j39fsnjdfqqi73i FOREIGN KEY (dish_id) REFERENCES public.dishes(id),
	CONSTRAINT fkme03hqeaw76c8vgbd20dwrogf FOREIGN KEY (ingredient_id) REFERENCES public.ingredients(id),
	CONSTRAINT fkprwghk7gqxpi2ywac266a4yru FOREIGN KEY (order_id) REFERENCES public.orders(id),
	CONSTRAINT fkquc2ny5ixvt3kq9nlrcm0ps37 FOREIGN KEY (dish_id,order_id) REFERENCES public.order_items(dish_id,order_id)
);










-- init data:
INSERT INTO public.customers (delivery_address, phone_number, join_date) VALUES
('ul. Zwycięstwa 12/4, 44-100 Gliwice', '500100200', '2026-01-15 10:30:00'),
('ul. Akademicka 5, 44-100 Gliwice', '600200300', '2026-02-20 14:15:00'),
('ul. Dolnych Wałów 8, 44-100 Gliwice', '700300400', '2026-03-05 09:00:00');


INSERT INTO public.ingredients (name, price, unit, allergen) VALUES
-- Average 25 PLN/L -> 0.025 per ml
('Sos pomidorowy San Marzano', 0.025, 'ml', NULL),
-- Average 70 PLN/KG -> 0.07 per g
('Mozzarella di Bufala', 0.070, 'g', '["mleko -lactose"]'),
-- Average 120 PLN/KG (fresh herbs are light but pricey) -> 0.12 per g
('Świeża bazylia', 0.120, 'g', NULL),
-- Average 65 PLN/KG -> 0.065 per g
('Szynka Prosciutto Cotto', 0.065, 'g', NULL),
-- Average 15 PLN/KG -> 0.015 per g
('Pieczarki', 0.015, 'g', NULL),
-- Average 95 PLN/KG -> 0.095 per g
('Salami Ventricina (ostre)', 0.095, 'g', NULL),
-- Average 85 PLN/KG -> 0.085 per g
('Ser Gorgonzola', 0.085, 'g', '["mleko -lactose"]'),
-- Average 110 PLN/KG -> 0.110 per g
('Ser Grana Padano', 0.110, 'g', '["mleko -lactose"]'),
-- Average 90 PLN/KG -> 0.090 per g
('Pancetta (włoski boczek)', 0.090, 'g', NULL),
-- Per unit price
('Świeże jaja', 1.200, 'szt', '["jaja"]'),
-- Average 45 PLN/KG -> 0.045 per g
('Mięso mielone wołowe', 0.045, 'g', NULL),
-- Average 130 PLN/KG -> 0.130 per g
('Mieszanka owoców morza', 0.130, 'g', '["mięczaki","skorupiaki"]'),
-- Per unit price (1 head/bulb avg)
('Czosnek', 1.500, 'szt', NULL),
-- Average 80 PLN/L -> 0.08 per ml
('Oliwa Extra Vergine', 0.080, 'ml', NULL),
-- Avg 60 PLN/KG -> 0.06 per g
('Ser niebieski', 0.060, 'g', '["mleko -lactose"]'),
-- Avg 55 PLN/KG -> 0.055 per g
('Camembert', 0.055, 'g', '["mleko -lactose"]'),
-- Avg 5 PLN/KG -> 0.005 per g
('Cebula', 0.005, 'g', NULL),
-- Avg 15 PLN/KG -> 0.015 per g
('Papryka', 0.015, 'g', NULL),
-- Avg 28 PLN/KG -> 0.028 per g
('Mięso mielone wieprzowe', 0.028, 'g', NULL),
-- Avg 12 PLN/KG -> 0.012 per g
('Pomidor', 0.012, 'g', NULL),
-- Avg 20 PLN/L -> 0.02 per ml
('Sos beszamelowy', 0.020, 'ml', '["mleko -lactose"]');


INSERT INTO public.dishes (name, price, description) VALUES
('Pizza Margherita', 32.00, 'Klasyczna pizza z sosem pomidorowym, mozzarellą i bazylią'),
('Pizza Capricciosa', 39.00, 'Pizza z szynką, pieczarkami i mozzarellą'),
('Pizza Quattro Formaggi', 44.00, 'Kompozycja czterech włoskich serów'),
('Pizza Diavola', 41.00, 'Ostra pizza z salami ventricina'),
('Spaghetti Carbonara', 36.00, 'Tradycyjna carbonara na pancetcie i żółtkach'),
('Tagliatelle al Ragu', 35.00, 'Szeroki makaron z wolno gotowanym ragu wołowym'),
('Penne al Pesto', 34.00, 'Makaron z domowym pesto bazyliowym'),
('Linguine ai Frutti di Mare', 49.00, 'Bogaty makaron z owocami morza'),
('Lasagne Klasyczna', 42.00, 'Pieczone warstwy makaronu z beszamelem i mięsem'),
('Gnocchi Sorrentina', 37.00, 'Kluski zapiekane z pomidorami i mozzarellą');


-- Mapping for Pizza Margherita (Dish 1)
INSERT INTO public.amount_of_ingredients (dish_id, ingredient_id, amount) VALUES
(1, 1, 100.0), -- 100ml Sos pomidorowy
(1, 2, 125.0), -- 125g Mozzarella
(1, 3, 5.0),   -- 5g Bazylia
(1, 14, 10.0); -- 10ml Oliwa

-- Mapping for Pizza Capricciosa (Dish 2)
INSERT INTO public.amount_of_ingredients (dish_id, ingredient_id, amount) VALUES
(2, 1, 100.0), -- Sos pomidorowy
(2, 2, 100.0), -- Mozzarella
(2, 4, 60.0),  -- Szynka Prosciutto Cotto
(2, 5, 50.0);  -- Pieczarki

-- Mapping for Pizza Quattro Formaggi (Dish 3)
INSERT INTO public.amount_of_ingredients (dish_id, ingredient_id, amount) VALUES
(3, 1, 80.0),   -- Sos pomidorowy (optional base)
(3, 2, 80.0),   -- Mozzarella
(3, 7, 40.0),   -- Ser Gorgonzola
(3, 8, 30.0);   -- Ser Grana Padano
(3, 15, 30.0);  -- Ser niebieski

-- Mapping for Pizza Diavola (Dish 4)
INSERT INTO public.amount_of_ingredients (dish_id, ingredient_id, amount) VALUES
(4, 1, 100.0), -- Sos pomidorowy
(4, 2, 100.0), -- Mozzarella
(4, 6, 70.0),  -- Salami Ventricina
(4, 14, 5.0);  -- Oliwa

-- Mapping for Spaghetti Carbonara (Dish 5)
INSERT INTO public.amount_of_ingredients (dish_id, ingredient_id, amount) VALUES
(5, 9, 80.0),  -- 80g Pancetta
(5, 10, 2.0),  -- 2 szt Jaja
(5, 8, 30.0),  -- 30g Grana Padano
(5, 13, 1.0);  -- 1 szt Czosnek

-- Mapping for Tagliatelle al Ragu (Dish 6)
INSERT INTO public.amount_of_ingredients (dish_id, ingredient_id, amount) VALUES
(6, 11, 120.0), -- Mięso mielone wołowe
(6, 1, 150.0),  -- Sos pomidorowy
(6, 13, 1.0),   -- Czosnek
(6, 8, 15.0);   -- Grana Padano

-- Mapping for Penne al Pesto (Dish 7)
INSERT INTO public.amount_of_ingredients (dish_id, ingredient_id, amount) VALUES
(7, 3, 30.0),   -- Świeża bazylia
(7, 14, 40.0),  -- Oliwa Extra Vergine
(7, 13, 1.0),   -- Czosnek
(7, 8, 20.0);   -- Grana Padano

-- Mapping for Linguine ai Frutti di Mare (Dish 8)
INSERT INTO public.amount_of_ingredients (dish_id, ingredient_id, amount) VALUES
(8, 12, 200.0), -- 200g Owoce morza
(8, 13, 2.0),   -- 2 szt Czosnek
(8, 14, 20.0),  -- 20ml Oliwa
(8, 1, 50.0);   -- 50ml Sos pomidorowy

-- Mapping for Lasagne Klasyczna (Dish 9)
INSERT INTO public.amount_of_ingredients (dish_id, ingredient_id, amount) VALUES
(9, 11, 150.0), -- Mięso mielone wołowe
(9, 1, 100.0),  -- Sos pomidorowy
(9, 21, 200.0), -- Sos beszamelowy
(9, 2, 60.0),   -- Mozzarella
(9, 8, 20.0);   -- Grana Padano
(9, 17, 40.0),  -- Cebula (for the ragu)

-- Mapping for Gnocchi Sorrentina (Dish 10)
INSERT INTO public.amount_of_ingredients (dish_id, ingredient_id, amount) VALUES
(10, 1, 120.0), -- Sos pomidorowy
(10, 2, 100.0), -- Mozzarella
(10, 3, 5.0),   -- Świeża bazylia
(10, 8, 15.0);  -- Grana Padano
(10, 20, 100.0), -- Pomidory świeże
(10, 13, 1.0);   -- Czosnek


